### ISSUE TITLE
Why don't you use a stringstream instead of the StringBuilder class?

### ISSUE THREAD

**Issue by michael-customlbs** [azadkuh/gason--#2]
That way I wouldn't have to deal with buffers that are too small.
Or how do you handle this problem that the buffer is too small?

**Comment by azadkuh** [comment]
I'd developed gason++ for an embedded system with an old toolchain (gcc 4.2), there was only a few KB of physical RAM available (a Cortex M4 uController), so STL was a no-go due to massive memory allocations. It's also forbidden to commit lots of alloc/free in embedded world.

this is the main reason gason++ re-uses the allocated memory (but gason doesn't).

On PC or smart phones where the requirement is totally different, you are absolutely right. there are more generous options!
